name: Aggregit

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  recordMetrics:
    runs-on: ubuntu-latest
    steps:
    - uses: michaeljolley/aggregit@v0.6
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        project_id: ${{ secrets.project_id }}
        private_key: ${{ secrets.private_key }}
        client_email: ${{ secrets.client_email }}
        firebaseDbUrl: ${{ secrets.firebaseDbUrl }}
